BOX = "debian/bookworm64"
SERVER_IP   = "192.168.56.110"
SERVER_NAME = "khanhayfS"

Vagrant.configure("2") do |config|
  config.vm.boot_timeout = 600
  config.vm.box = BOX
  
  # Allocate hardware resources for the server VM
  config.vm.provider "virtualbox" do |vb|
    vb.name = SERVER_NAME
    vb.memory = 2048
    vb.cpus   = 2
  end

  config.vm.define SERVER_NAME do |server|
    server.vm.hostname = SERVER_NAME
    server.vm.network "private_network", ip: SERVER_IP

    # confs/ becomes available on the VM at /vagrant/confs
    # Install K3s and configure the control plane
    server.vm.provision "shell",
      path: "scripts/server.sh",
      args: [SERVER_IP]
    
    # Deploy the Kubernetes resources
    server.vm.provision "shell",
      path: "scripts/deploy.sh"
  end
end