# Cluster configuration
# ---------------------------------------------------------------------------------------------------------------
SERVER_NAME = "khanhayfS"
SERVER_IP = "192.168.56.110"

WORKER_NAME = "khanhayfSW"
WORKER_IP = "192.168.56.111"

# Use Vagrant Configuration Version 2
Vagrant.configure("2") do |config|

  # common configuration shared by both VMs
  # ---------------------------------------------------------------------------------------------------------------
  # Allow extra time since K3s installation can take several minutes
  config.vm.boot_timeout = 600
  # define which OS image vagrant will use
  config.vm.box = "debian/bookworm64"

  # allocate hardware resources for each VM
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 1
  end

  # create a VM for the server node
  # ---------------------------------------------------------------------------------------------------------------
  config.vm.define SERVER_NAME do |server|
    # sets the Linux hostname
    server.vm.hostname = SERVER_NAME
    
    # assign a static private IP so the worker can reach the server
    server.vm.network "private_network", ip: SERVER_IP
    # This automatically creates a Host-only adapter
    
    # install and configure the K3s server
    server.vm.provision "shell", path: "scripts/server.sh"
  end

  # create the worker node
  # ---------------------------------------------------------------------------------------------------------------
  config.vm.define WORKER_NAME do |worker|
    # sets the Linux hostname
    worker.vm.hostname = WORKER_NAME

    # assign a static private IP used to communicate with the server
    worker.vm.network "private_network", ip: WORKER_IP

    # provision the K3s worker node and join it to the cluster
    worker.vm.provision "shell", path: "scripts/worker.sh" 
  end
end
