#!/bin/bash

# server IP address and location of the node join token generated by K3s
IP="192.168.56.110"
TOKEN="/var/lib/rancher/k3s/server/node-token"

# update package lists and install curl
apt-get update -y
apt-get install -y curl

# install and start the K3s server as the control plane node
curl -sfL https://get.k3s.io | sh -s - server --node-ip="$IP" --write-kubeconfig-mode=644

# wait until the K3s node reaches the Ready state
kubectl wait --for=condition=Ready node --all --timeout=180s

# store the token generated by the server in a shared directory so that the worker can access it
mkdir -p /vagrant/confs
cp "$TOKEN" /vagrant/confs/node-token

echo "------------------------------------------------------------------------------------------------------------"
echo "K3s server is ready"
echo "------------------------------------------------------------------------------------------------------------"
