#!/bin/bash

# define the IP address of the server and the path to the join token
IP="192.168.56.110"
TOKEN="/var/lib/rancher/k3s/server/node-token"

# update package lists and install curl
apt-get update -y
apt-get install -y curl

# Install and start the K3s server as the control plane node
curl -sfL https://get.k3s.io | sh -s - server \
    --bind-address="$IP" \
    --node-ip="$IP" \
    --write-kubeconfig-mode=644

# Wait until the API server responds and the control plane is ready to accept connections
until kubectl get nodes >/dev/null 2>&1
do
    sleep 2
done

# Store the tocken generated by the server in a shared directory so that the worker can access it
mkdir -p /vagrant/confs
cat "$TOKEN" > /vagrant/confs/node-token
